#!/bin/sh
# Time : 2019/02/25 14:24
# Author : 
# File : ${NAME}.sh
# Describe:统计 接口统计时间
#
# Change:2019-02-25 统计时间以增量开始时间为准，不用系统时间
startsec=$(date +%s)
source /data/etlscript/PUBLIC/SCRIPT/TOOL/scriptHelper.sh
resoveJson $1
hivejdbc="jdbc:hive2://${src_ip}:${src_port}"
checkLogPath $task_name
exec &> $CMRH_DATAHUB_SCRIPT_LOG/$EXE_DATE/$task_name/$run_serial_no.log

job_name=$0

# 第二段：SQL直接写在脚本中
## 开发 ###################################
pdate=${inc_start:0:8}
jdate=`date -d "$pdate" +%s`
kdate=`date -d @$jdate "+%Y-%m-%d"`

ndate=${inc_end:0:8}
fdate=`date -d "$ndate" +%s`
edate=`date -d @$fdate "+%Y-%m-%d"`

pdate=${inc_start:0:8}
begin_date=${pdate:0:4}"-"${pdate:4:2}"-"${pdate:6:2}

mysqljdbc="jdbc:mysql://$dest_ip:$dest_port/$dest_dbname?useUnicode=true&characterEncoding=utf-8"
yesterday=`date -d "-1 day " +%Y-%m-%d`
beeline -u $hivejdbc -n $src_user -p $src_password -e "
SET mapred.job.queue.name=${hive_queue};
SET MAPRED.JOB.NAME=${job_name};
use cmrh_cmcs;

insert overwrite table ods_cmrh_bas_t_interface_call_count partition (pdate='${begin_date}')
select service_name,
       t.request_uri,
       t.request_source,
       t.call_total,
       nvl((t.call_total - t.call_failure), 0) call_success,
       t.call_failure,
       avg_response_time,
       max_response_time,
       min_response_time,
       t.call_date,
       t.call_type,
       t.create_time,
       t.create_user,
       t.change_time,
       t.chang_user
  from (select service_name,
               request_uri,
               cust_source as request_source,
               count(1) call_total,
               count(case when result_code != '200' and lower(nvl(exception,'null')) != 'null' and exception != '' then 1 end) call_failure,
               round(avg(cast(time_cost as int)), 3) avg_response_time,
               max(cast(time_cost as int)) max_response_time,
               min(cast(time_cost as int)) min_response_time,
               to_date(t.create_time) call_date,
               '0' call_type,
               from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') create_time,
               'sys' create_user,
               from_unixtime(unix_timestamp(), 'yyyy-MM-dd HH:mm:ss') change_time,
               'sys' chang_user
          from cmft_cmcs.ods_mams_t_interface_logs t
         where  pdate='${begin_date}' and to_date(create_time)='${begin_date}'
         group by service_name,
                  request_uri,
                  cust_source,
                  to_date(t.create_time)) t;

";

sqoop eval \
--connect $mysqljdbc \
--username $dest_user \
--password $dest_password \
--query "delete from t_interface_logs where call_date='${begin_date}';"


sqoop export \
--connect $mysqljdbc \
--username $dest_user \
--password $dest_password \
--table t_interface_logs -m 1 \
--export-dir /user/hive/warehouse/cmrh_cmcs.db/ods_cmrh_bas_t_interface_call_count/pdate=${begin_date} \
--input-fields-terminated-by '\001' \--input-null-string '\\N' \--input-null-non-string '\\N' \
# 检查执行状况
exitCodeCheck $? $startsec $run_serial_no $task_name
## 结束任务 ###################################
endsec=$(date +%s)
message="脚本耗时: $[ endsec-startsec ] 秒"
echo $message

# 回调 调度系统
callDatahub 0 "$message" "$run_serial_no" "$task_name"



